name: task_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.7
  email_validator: '^2.1.16'
  fluttertoast: ^8.0.9
  json_serializable: ^6.3.1
  device_info_plus: ^8.0.0
  modal_bottom_sheet: ^2.0.1
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.4
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^12.0.1+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true